export const types = Object.freeze({
  //Sync
  TASK_FILL: "TASK_FILL",
  TASK_TOGGLE_FORM: "TASK_TOGGLE_FORM",
  TASK_CREATE: "TASK_CREATE",
  TASK_SELECT: "TASK_SELECT",
  TASK_CREATE_NEW: "TASK_CREATE_NEW",
  //Async
  TASK_FETCH_ASYNC: "TASK_FETCH_ASYNC",
  TASK_SET_FETCHING_ERROR: `TASK_SET_FETCHING_ERROR`,
  TASK_START_FETCHING: `TASK_START_FETCHING`,
  TASK_STOP_FETCHING: `TASK_STOP_FETCHING`,
});
