export const root = `https://lab.lectrum.io/rtx/api`;
export const bearerToken = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtyaW1zLnJ1c2xhbkBnbWFpbC5jb20iLCJpYXQiOjE2MTk2NzI4NjcsImV4cCI6MTYyMDg4MjQ2NywiaXNzIjoiTGVjdHJ1bSBMTEMifQ.gJ2CIHbsXSCLCSwPEnIKxC3C0IV8492SHCaSbmdoN4Q`;
